2024-09-24 16:01:54,969 | WARNING | Неверный тип данных для объекта Runner
2024-09-24 16:01:54,970 | WARNING | Traceback (most recent call last):
  File "C:\Users\radag\homework 2\pythonProject8\.venv\My_chall_part12\module_12_4\test_12_4_1.py", line 83, in test_run
    runner2 = Runner(24,5)
              ^^^^^^^^^^^^
  File "C:\Users\radag\homework 2\pythonProject8\.venv\My_chall_part12\module_12_4\test_12_4_1.py", line 17, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-09-24 16:01:54,970 | WARNING | Неверная скорость для Runner
2024-09-24 16:01:54,971 | WARNING | Traceback (most recent call last):
  File "C:\Users\radag\homework 2\pythonProject8\.venv\My_chall_part12\module_12_4\test_12_4_1.py", line 70, in test_walk
    runner1 = Runner('11', -5)
              ^^^^^^^^^^^^^^^^
  File "C:\Users\radag\homework 2\pythonProject8\.venv\My_chall_part12\module_12_4\test_12_4_1.py", line 22, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

